### ISSUE TITLE
No such file or directory : '../asset/fixedmat_viz.npy'  Error

### ISSUE THREAD

**Issue by dangdang2222** [TaoHuUMD/SurMo#1]
Thank you for your great work and sharing.
I've got some error, FileNotFoundError: [Errno 2] No such file or directory: '../asset/fixedmat_viz.npy'.
Can you share the solution?
<img width="605" alt="스크린샷 2024-07-02 211357" src="https://github.com/TaoHuUMD/SurMo/assets/64007947/a7ed9a4f-ec92-4623-8bad-75d65b80f1de">

**Comment by TaoHuUMD** [comment]
Thanks for your interest. The file has been uploaded to the [OneDrive directory ](https://onedrive.live.com/?id=CD958C29FFD57DDB%213600&cid=CD958C29FFD57DDB).

**Comment by dangdang2222** [comment]
Thank you for your reply. 

But when I go into the onedrive link you sent me, it says, "The item does not exist or is not available. The item has been deleted or expired, or you do not have permission to view its contents. Please contact the owner for more information on this item." 

Would it be possible to check it?

**Comment by TaoHuUMD** [comment]
Hi, I did not find a problem with the shared directory. Maybe the right of the shared directory is changed when new files are uploaded. I shared the directory again with [new links](https://1drv.ms/f/s!Att91f8pjJXNnBBDe3pVC-vTbG_a?e=WDcxSS), and it should work now.
