### ISSUE TITLE
ImportError: cannot import name 'vis_high_dimension_img' from 'uvm_lib.engine.thutil.num' (SurMo\uvm_lib\engine\thutil\num.py) 

### ISSUE THREAD

**Issue by hhxphh** [TaoHuUMD/SurMo#3]
ImportError: cannot import name 'vis_high_dimension_img' from 'uvm_lib.engine.thutil.num' (SurMo\uvm_lib\engine\thutil\num.py) 

In SurMo\uvm_lib\engine\lib\models\base_model.py 
from uvm_lib.engine.thutil.num import vis_high_dimension_img, plot_scat
but I didn't find vis_high_dimension_img and  plot_scat in SurMo\uvm_lib\engine\thutil\num.py

**Comment by TaoHuUMD** [comment]
Updating soon.

**Comment by hhxphh** [comment]
Thank you very much. In fact, there are other errors besides this one. The main reason is that the folder path does not correspond to the directory format given in the readme. It would be a pity if such a good work limited its promotion because of such a trivial flaw, thank you very much again for your reply, very good work.

**Comment by hhxphh** [comment]
I've sorted out some of the code issues I've had (some of which may be my own) and I hope it helps. Thank you.
[error.txt](https://github.com/user-attachments/files/17975349/error.txt)
